# マップの更新間の時間（秒単位）。 これを低く設定すると、マップがより頻繁に更新されます。 ただし、より大きな計算負荷が必要になります。 このパラメーターの設定は、環境によって異なります。
map_update_interval: 2.0
# このパラメーターは、LIDARセンサーの最大使用可能範囲を設定します。 xは新しい値を意味しています。
maxUrange: 15.0
# センサーの最大範囲。センサーの範囲内に障害物がない領域がマップ内の空きスペースとして表示される場合は、maxUrange < 実際のセンサーの最大範囲 <= maxRange に設定します。
# maxRange: 30.0
# マッチングを行なう際の標準偏差。(sell) loop closureのマッチングの誤差に関するパラメータか。
sigma: 0.05
# 対応関係を検索するカーネル、スキャン一致プロセスの検索ウィンドウ。対応するカーネル サイズ。主にスコアの計算時に検索されるサイズに使用されます。
kernelSize: 1
# トランスレーションの最適化ステップ
lstep: 0.05
# ローテーションの最適化ステップ
astep: 0.05
# スキャンマッチングの反復回数
iterations: 5
# 尤度の計算に使用されるビームのシグマ
lsigma: 0.075
# リサンプリング効果を平滑化するために、尤度を評価する際に使用されるゲイン
ogain: 3.0
# 各スキャンでスキップするビームの数。一致を計算するために (n+1) 番目ごとのレーザー光線のみを取得します (0 = すべての光線を取得します)
lskip: 0
# スキャンマッチングの結果を考慮するための最小スコア。 このパラメーターにより、ポーズ推定のジャンプを回避できます。 これが適切に設定されている場合は、（Slamのノードが起動しているターミナルで）以下の情報を見ることができます。
minimumScore: 50
# 平行移動の関数としての平行移動におけるオドメトリ エラー (rho/rho)
srr: 0.1
# 回転の関数としての平行移動におけるオドメトリ誤差 (rho/theta)
srt: 0.2
# 平行移動の関数としての回転時のオドメトリ誤差 (シータ/ロー)
str: 0.1
# 回転の関数としての回転時のオドメトリ誤差 (シータ/シータ)
stt: 0.2
# スキャン処理を行うロボットの移動距離のしきい値。
linearUpdate: 1.0
# スキャン処理を行うロボットの回転のしきい値。 これをlinearUpdateよりも小さく設定することを推奨します。
angularUpdate: 0.2
# 最後に処理されたスキャンが更新時間 (秒単位) よりも古い場合、スキャンを処理します。ゼロ未満の値を指定すると、時間ベースの更新がオフになります。
temporalUpdate: 0.5
# Neff ベースのリサンプリングしきい値
resampleThreshold: 0.5
# パーティクルフィルター内の粒子の数
particles: 100
# 初期マップ サイズ (メートル単位)
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
# マップの解像度 (占有グリッドセルあたりのメートル単位)
delta: 0.05
# 尤度の並進サンプリング範囲
llsamplerange: 0.01
# 尤度のトランスレーショナル サンプリング ステップ
llsamplestep: 0.01
# 尤度の角度サンプリング範囲
lasamplerange: 0.005
# 尤度の角度サンプリング ステップ
lasamplestep: 0.005
